name = "M_stopwatch"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.com"
copyright = "Copyright 2021, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = true
